drop table if exists items;
create table items (
         id bigint generated by default as identity,
         price bigint,
         description varchar(255),
         img_path varchar(255),
         title varchar(255),
         primary key (id)
);
drop table if exists carts;
create table carts (
         id bigint generated by default as identity,
         user_id bigint,
         primary key (id)
);
drop table if exists cart_items;
create table cart_items (
         id bigint generated by default as identity,
         cart_id bigint not null,
         item_id bigint,
         item_title varchar(255),
         item_count integer,
         primary key (id)
);
drop table if exists orders;
create table orders (
         id bigint generated by default as identity,
         primary key (id)
);
drop table if exists order_items;
create table order_items (
         id bigint generated by default as identity,
         item_count integer,
         order_id bigint not null,
         item_id bigint
);
------------------------------------


--INSERT INTO items (title, description, img_path, price)
--VALUES ('Бейсболка черная', 'Очень модная бейсболка черного цвета', '2.jpg', 1500);
--
--INSERT INTO items (title, description, img_path, price)
--VALUES ('Бейсболка красная', 'Очень модная бейсболка красного цвета', '1.jpg', 1500);
--
--INSERT INTO items (title, description, img_path, price)
--VALUES ('Футбольный мяч', 'Классный мяч для игры в футбол', '4.jpg', 400);
--
--INSERT INTO items (title, description, img_path, price)
--VALUES ('Зонтик', 'Зонтик, который всегда пригодится', '3.jpg', 2000);